stages:
  - test
  - build

workflow:
  rules:
    - if: '$CI_PIPELINE_SOURCE == "push"'
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
    - when: never

variables:
  COMPOSER_ALLOW_SUPERUSER: 1

.default_php: &default_php
  image: php:8.3
  before_script:
    - apt-get update -y
    - apt-get install -y unzip git curl libzip-dev libpng-dev libonig-dev libxml2-dev zip
    - docker-php-ext-install pdo_mysql mbstring exif pcntl bcmath gd zip
    - pecl install redis
    - docker-php-ext-enable redis
    - curl -sS https://getcomposer.org/installer | php
    - mv composer.phar /usr/local/bin/composer
  cache:
    key: "${CI_PROJECT_NAME}-${CI_JOB_NAME}"
    paths:
      - vendor/

core-tests:
  <<: *default_php
  stage: test
  script:
    - cd priorix-core
    - composer install --no-interaction --prefer-dist --optimize-autoloader
    - cp .env.example .env
    - php artisan key:generate --ansi
    - composer test

gamification-tests:
  <<: *default_php
  stage: test
  script:
    - cd priorix-gamification
    - composer install --no-interaction --prefer-dist --optimize-autoloader
    - cp .env.example .env
    - php artisan key:generate --ansi
    - composer test

frontend-tests:
  image: node:22
  stage: test
  cache:
    key: "${CI_PROJECT_NAME}-${CI_JOB_NAME}"
    paths:
      - client/node_modules/
  script:
    - cd client
    - npm ci
    - npm run test

docker-build:
  image: docker:24.0.5
  stage: build
  needs: [core-tests, gamification-tests, frontend-tests]
  services:
    - name: docker:24.0.5-dind
      alias: docker
  variables:
    DOCKER_HOST: tcp://docker:2375/
    DOCKER_TLS_CERTDIR: ""
  script:
    - docker info
    - docker build -t priorix-core:ci priorix-core
    - docker build -t priorix-gamification:ci priorix-gamification
