apiVersion: v1
kind: Secret
metadata:
  name: priorix-secrets
  namespace: priorix
type: Opaque
stringData:
  DB_PASSWORD: secret
  MYSQL_ROOT_PASSWORD: root
  REDIS_PASSWORD: ""
  JWT_SECRET: doDEtIR5D2y6DJ7ws7zrMX3QT79FgMleOkUvcU2dZcnvx4ZqhYA3ouNa3tKZlqZD
  INTERNAL_SERVICE_SECRET: MHJ9q5+s0YeULKmD0F+DcvXcUgjhI9/GXjX5XqGEg7Q=
