# Identificación del proyecto
sonar.projectKey=dyas-priorix_priorix-gamification
sonar.projectName=Priorix Gamification
sonar.projectVersion=1.0

# Organización en SonarCloud
sonar.organization=dyas-priorix

# Código fuente
sonar.sources=app
sonar.tests=tests

# Exclusiones
sonar.exclusions=vendor/**,bootstrap/cache/**,storage/**,public/**,database/migrations/**,resources/views/**
sonar.test.exclusions=vendor/**

# PHP
sonar.language=php

# Cobertura
sonar.php.coverage.reportPaths=coverage.xml

# Encoding
sonar.sourceEncoding=UTF-8
