$kind: http-request
name: Get Today Pending Tasks
method: GET
url: '{{base_url_core}}/tasks/today/pending'
order: 1600
headers:
  - key: Authorization
    value: 'Bearer {{token}}'
tests: |-
  pm.test("Status is 200 OK", function () {
    pm.response.to.have.status(200);
  });

  pm.test("Response is an array", function () {
    const jsonData = pm.response.json();
    pm.expect(jsonData).to.be.an('array');
  });
