[SERVICE]
    Flush        5
    Daemon       Off
    Log_Level    info

[INPUT]
    Name              tail
    Path              /var/log/priorix/core/*.log
    Tag               priorix.core
    Refresh_Interval  5
    Read_from_Head    On

[INPUT]
    Name              tail
    Path              /var/log/priorix/gamification/*.log
    Tag               priorix.gamification
    Refresh_Interval  5
    Read_from_Head    On

[OUTPUT]
    Name            es
    Match           priorix.*
    Host            elasticsearch
    Port            9200
    Index           priorix-logs
    Suppress_Type_Name On
    Logstash_Format On
    Logstash_Prefix priorix
