apiVersion: v1
kind: Service
metadata:
  name: priorix-gamification
spec:
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: priorix-gamification
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: priorix-gamification
spec:
  replicas: 2
  selector:
    matchLabels:
      app: priorix-gamification
  template:
    metadata:
      labels:
        app: priorix-gamification
    spec:
      containers:
        - name: gamification
          image: priorix-gamification:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          envFrom:
            - configMapRef:
                name: priorix-config
            - secretRef:
                name: priorix-secrets
          env:
            - name: DB_HOST
              value: mysql-gamification
            - name: DB_DATABASE
              value: priorix_gamification
          readinessProbe:
            httpGet:
              path: /metrics
              port: 80
            initialDelaySeconds: 20
            periodSeconds: 10
