apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: priorix

resources:
  - namespace.yaml
  - configmap.yaml
  - secret.yaml
  - mysql-core.yaml
  - mysql-gamification.yaml
  - redis.yaml
  - core.yaml
  - gamification.yaml
  - nginx-config.yaml
  - nginx.yaml
  - prometheus.yaml
  - grafana.yaml
