apiVersion: v1
kind: Service
metadata:
  name: mysql-core
spec:
  ports:
    - port: 3306
  selector:
    app: mysql-core
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-core
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql-core
  template:
    metadata:
      labels:
        app: mysql-core
    spec:
      containers:
        - name: mysql
          image: mysql:8.0
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: priorix-secrets
                  key: MYSQL_ROOT_PASSWORD
            - name: MYSQL_DATABASE
              value: priorix_core
            - name: MYSQL_USER
              valueFrom:
                configMapKeyRef:
                  name: priorix-config
                  key: DB_USERNAME
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: priorix-secrets
                  key: DB_PASSWORD
          ports:
            - containerPort: 3306
