apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    uid: prometheus # ← este uid debe coincidir exactamente con el dashboard JSON
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: false
