apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

images:
  - name: priorix-core
    newName: ghcr.io/brayan-137/dyas-priorix/priorix-core
    newTag: latest
  - name: priorix-gamification
    newName: ghcr.io/brayan-137/dyas-priorix/priorix-gamification
    newTag: latest

patches:
  - target:
      kind: Deployment
      name: priorix-core
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 3
  - target:
      kind: Deployment
      name: priorix-gamification
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 3
